apiVersion: kubelab.io/v1alpha1
kind: LabPackage
metadata:
  labId: lab-012-pvc-pending
  version: 1.0.0
  publisherId: kubelab
  publisherName: KubeLab Project
spec:
  requiresKubelab: ">=0.6.0a0,<0.7.0"
