apiVersion: v1
kind: PersistentVolumeClaim
metadata: {name: app-data, namespace: kubelab-pvc-claim-missing}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: standard
  resources: {requests: {storage: 128Mi}}
