apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: kubelab-service-selector
spec:
  selector:
    app: service-selector-lab
  ports:
    - name: http
      port: 80
      targetPort: http
