apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: {name: web, namespace: kubelab-ingress-backend-port}
spec:
  ingressClassName: nginx
  rules:
    - host: web.kubelab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port: {number: 80}
